create table account_transaction (id integer generated by default as identity, change numeric(12,4) not null, timestamp TIMESTAMP not null, user_id bigint not null, primary key (id));
create table tuplaus_game (id bigint generated by default as identity, game_end TIMESTAMP, game_start TIMESTAMP not null, initial_bet numeric(12,4) not null, user_id bigint not null, primary key (id));
create table tuplaus_game_event (id bigint generated by default as identity, bet numeric(12,4) not null, card integer not null, pick smallint not null, pot numeric(12,4) not null, timestamp TIMESTAMP not null, game_id bigint not null, primary key (id));
create table usr (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
alter table if exists account_transaction add constraint FKc20kcwlj2895smhnpyrbixc53 foreign key (user_id) references usr;
alter table if exists tuplaus_game add constraint FKgsrfiw2801843w3spxd97t7dt foreign key (user_id) references usr;
alter table if exists tuplaus_game_event add constraint FKropodvrtjfneytx4bgqi5ibdg foreign key (game_id) references tuplaus_game;
